import { discoverNetwork as apiDiscover, saveNetwork as apiSave } from './api';

export const discoverNetwork = async (networkRange) => {
  const devices = await apiDiscover(networkRange);
  return {
    topology_data: JSON.stringify({
      nodes: devices,
      links: [] // Will be generated by the backend
    }),
    devices
  };
};

export const saveNetwork = async (networkData) => {
  return apiSave({
    name: networkData.name,
    description: `Network discovered on ${new Date().toLocaleDateString()}`,
    devices: networkData.devices
  });
};
